### ISSUE TITLE
Please add support for some SAMD21 boards:

### ISSUE THREAD

**Issue by malachib** [platformio/platformio#520]
* Sparkfun SAMD dev / mini
* Adafruit M0 feather series (I expect all of them would work as one single feather m0 target)

I've been using the zeroUSB profile to (very effectively!) program my SAMD with platformio but technically it's the wrong PID and might eventually cause issues.  Have not tried my adafruit yet

**Comment by thirstyfish** [comment]
+1

Have you managed to get the Adafruit Feather m0 Wifi board working?
( I'm referring to this one: https://learn.adafruit.com/adafruit-feather-m0-wifi-atwinc1500?view=all )
I tried to get it to work with the zeroUSB config, but it was missing analog PINs I'm using, so I tried to hack it together by copying the relevant pieces over from
_~/Library/Arduino15/packages/adafruit/hardware/samd_ (e.g. the variant files), but then I had some other issues unfortunately trying to compile the Adafruit-GFX-Library:

`.pioenvs/zeroUSB/Adafruit-GFX-Library/fontconvert/fontconvert.c:23:22: fatal error: ft2build.h: No such file or directory`

**Comment by malachib** [comment]
Haven't tried the Adafruit yet (mine is the coveted BLE version) but I expect similar results as yours

**Comment by aethaniel** [comment]
@ivankravets, this ticket should not be labelled vendor:atmel :wink: as the issue seems to be in OSX, maybe around user rights to read/write on a system peripheral (cu.usbmodem1411 in this case).

The boards listed here are compatible with Arduino Zero, thus the label vendor:arduino or arch:sam should be added instead

**Comment by malachib** [comment]
I believe I've discovered what aggravates this problem.  I observe similar behaviors on my debian machine.

I theorize that some component of the build chain attempts to invoke bossac with something like "/dev/cu.usbmodem1411" and fails because it must be formatted only as "cu.usbmodem1411".

**Comment by ivankravets** [comment]
@malachib what do you see for `pio serialports list`?

**Comment by malachib** [comment]
For the record, pio run -t upload frequently works on my debian machine (haven't been using it on the mac lately).  Once in a while it fails and seems to leave it in a state which I must run manual bossac to recover.  Debian results of `pio serialport list`

While the device is out of programming mode, we see:

```
/dev/ttyS0
----------
Hardware ID: PNP0501
Description: ttyS0

/dev/ttyACM0
------------
Hardware ID: USB VID:PID=2341:804D LOCATION=2-2.1
Description: Arduino Zero

```

While in programming mode (put there on purpose, not accidentally reached), we see:

```
/dev/ttyS0
----------
Hardware ID: PNP0501
Description: ttyS0

/dev/ttyACM0
------------
Hardware ID: USB VID:PID=1B4F:0D21 LOCATION=2-2.1
Description: ttyACM0

```

**Comment by ivankravets** [comment]
PlatformIO uses `pio serialport list` results before upload. I can't imagine how you receive `cu.usbmodem1411` instead `/dev/cu.usbmodem1411`... 😢

**Comment by malachib** [comment]
I'm thinking the opposite is happening.  BOSSAC expects no /dev/ prefix and maybe one is present sometimes?   Just a theory only

**Comment by ivankravets** [comment]
> BOSSAC expects no /dev/ prefix

@valeros is it true?

**Comment by malachib** [comment]
Another tidbit - on debian today.  I'm discovering sparkfun board seems to need up to a 20s ish delay after entering program mode before it will accept programming.  Also, today pio isn't able to program it at all - the "state" described above (7d ago) seems to be program mode - which pio always succeeds at getting the device into.

**Comment by tabchas** [comment]
Also having problems uploading to Adafruit Feather. Any ideas of a fix? This is only reason I'm still using the regular Arduino IDE.

**Comment by ivankravets** [comment]
@tabchas , @malachib , looks like the issue with uploading has been fixed today. Could you try http://docs.platformio.org/en/latest/installation.html#development-version ?

**Comment by malachib** [comment]
Willdo - thanks Ivan!

**Comment by tabchas** [comment]
@malachib Does it work for you?

I still get an error during upload.

**Comment by malachib** [comment]
I am trying on my Mac right now and it's behaving well.  However:

* I'm not sure if I'm running the dev version of platformio here (@ivankravets how do I check?)
* Haven't tested on the Mac in a while.  So maybe a false positive.  Gonna try my linux box shortly

Side note: almost blew up my SAMD today.  It still works, so the hunt for where that smoke was coming from continues =)

**Comment by ivankravets** [comment]
@tabchas what is your OS? I've pushed new updates to development version (2.9.3.dev0). Could you try new build? See instructions http://docs.platformio.org/en/latest/installation.html#development-version

**Comment by ivankravets** [comment]
@malachib 
> I'm not sure if I'm running the dev version of platformio here

Do you use PlatformIO IDE? Check CLI version via `Menu: PlatformIO > Home screen`.

**Comment by malachib** [comment]
OK:

Mac: platformio 2.9.2
Debian: platformio 2.9.3.dev0

Unfortunately Debian still not playing nice.  Mac passes basic tests (cool!).  Following is for Debian only:

# Scenario A

If I do `pio run -t upload` it will:

a) promptly put device into program mode 
b) error out with:

```
No device found on ttyACM0
scons: *** [upload] Error 1
```

at which point `pio run -t upload` will only generate 

```
Set binary mode
No device found on ttyACM0
Send auto-baud
Set binary mode
scons: *** [upload] Error 1
```

 so I must proceed to c) run manual bossac for successful upload (no sudo needed)

----
# Scenario B

If I do `sudo pio run -t upload` it sometimes manages to upload successfully, after trying a few times getting errors like:

```
Set binary mode
Send auto-baud
Set binary mode
readWord(addr=0)=0x200023a0
readWord(addr=0xe000ed00)=0x410cc601
readWord(addr=0x41002018)=0x10010205
version()=v1.1 [SparkFun:XYZ] Sep 24 2015 16:50:58
chipId=0x10010005
Connected at 115200 baud
readWord(addr=0)=0x200023a0
readWord(addr=0xe000ed00)=0x410cc601
readWord(addr=0x41002018)=0x10010205
Atmel SMART device 0x10010005 found
write(addr=0x20004000,size=0x34)

SAM-BA operation failed
```

Sometimes not, in which case I have to run my manual bossac many many times to coax it back into working again

**Comment by tabchas** [comment]
Upload works! I selected "Arduino Zero - Native USB Port" and am using the Adafruit Feather Bluefruit M0 board.

Thanks guys!

**Comment by ivankravets** [comment]
@tabchas what is your OS?

**Comment by tabchas** [comment]
@ivankravets I am on OSX 10.11.5

**Comment by ivankravets** [comment]
@tabchas thanks a lot for the report. Yes, the latest PlatformIO 2.9.4 should work very well on the Mac and Windows. 

We have the one issue with Linux - `udev` rules. User have to specify valid PID/VID `udev` rules for the SAM-BA based board. The one rule should be specified for the default Native USB port and other for the PROGRAM/BOOTLOADER serial port.

**Comment by valeros** [comment]
Added support for several SAMD21 based boards:
```
mkr1000USB
adafruit_feather_m0_usb
sparkfun_samd21_dev_usb
sparkfun_samd21_mini_usb
```
Please install PlatformIO [dev version](http://docs.platformio.org/en/latest/installation.html#development-version) and update `framework-arduinosam` package via `platformio update`
Special thanks to @malachib for providing a test board!

**Comment by ivankravets** [comment]
@malachib does it work for you?

**Comment by malachib** [comment]
Using pio version 2.10.4.dev2 and the newest udev rules as of today.

Debian results are very positive.  Initial attempt at `pio run -t upload` yields a fully successful upload!  Subsequent attempts fail with:

`scons: *** [upload] could not open port /dev/ttyACM0: [Errno 16] Device or resource busy: '/dev/ttyACM0'
`

which can be overcome either by:

1.  running `sudo pio run -t upload` 
2.  waiting a certain amount of time (seems to be over a minute)

FYI I also tried this on an Ubuntu 16.04 box using the versions described on the first line.

The results are similar to my Jun 3rd post *except* that `sudo pio run -t upload` does seem to consistently upload to the device after a few tries.

**Comment by ivankravets** [comment]
@malachib do you use this `board = sparkfun_samd21_dev_usb`? Check that 2 USB devices (in boot mode and without) are listed in udev rules

**Comment by malachib** [comment]
I am indeed using `board = sparkfun_samd21_dev_usb`

I'll get back to you on the udev rules -

**Comment by ivankravets** [comment]
@malachib do you have any news?

**Comment by valeros** [comment]
Hi @malachib! Does upload process work well in Arduino IDE?
Probably this issue isn't linked with your udev rules. I've found some information about this problem on the [SparkFun website](https://learn.sparkfun.com/tutorials/samd21-minidev-breakout-hookup-guide/setting-up-arduino) (at the bottom of the page) and looks like it's a known issue with their board.

**Comment by ivankravets** [comment]
@malachib I propose to open a new issue with detailed description about your problem. I'm going to make release with the other boards that described here.

**Comment by malachib** [comment]
Sorry been out of town!  I'll try out Arduino IDE and get back to you
